application: wami-recorder
version: 1
runtime: python
api_version: 1

handlers:
- url: /crossdomain.xml
  mime_type: text/xml
  static_files: public/crossdomain.xml
  upload: public/crossdomain.xml

- url: /list
  script: python/list.py
  login: admin

- url: /audio
  script: python/sessions.py

- url: /client
  static_dir: public/client

- url: /turk
  static_dir: public/turk
